### ISSUE TITLE
2ami is not called

### ISSUE THREAD

**Issue by art-lucas** [endorama/ulauncher-two-factor-authenticator#5]
Thanks for making this extension available. I've installed `2ami` in `/usr/local/bin/` but it seems that it can't be found by the keyword "2fa" in ulauncher as it doens't list any entries, which are displayed in the terminal with `2ami list`. Could you tell me where the `2ami` binary should be placed? Thank you.

**Comment by art-lucas** [comment]
From what I understand, the script `~/.local/share/ulauncher/extensions/com.github.endorama.ulauncher-two-factor-authenticator/main.py` needs the binary to be named `two-factor-authenticator`:

```
 16 #twoFactorAuthenticatorCommand = "two-factor-authenticator"
 17 twoFactorAuthenticatorCommand = "two-factor-authenticator"
 18 generateCommand = twoFactorAuthenticatorCommand + " generate %s --clip"
 19 listCommand = twoFactorAuthenticatorCommand + " list"
```

So I created a symlink `2ami` -> `two-factor-authenticator` in `/usr/local/bin/`, then modified the Py script:
` 17 twoFactorAuthenticatorCommand = "/usr/local/bin/two-factor-authenticator"`

It works now. I'm sure that's not the right way to go about it as the modif would be lost after a script update.

**Comment by art-lucas** [comment]
I'm facing another issue now: the copy-to-clipboard doesn't seem to work, i.e., there's no 2FA in CTRL-V or the clipboard.

**Comment by tukanos** [comment]
I think it is better to rename it directly in the plugin.  The copy to clipboard then works correctly.

Here is my simple patch: https://github.com/endorama/ulauncher-two-factor-authenticator/pull/7

**Comment by endorama** [comment]
hello, sorry I completely missed the notifications for these issues :sweat_smile:. I'll take some time to review both & the PR and get back to you.

**Comment by endorama** [comment]
I merged the PR from @tukanos, if you update the extension it should not work as expected, if you have installed 2ami.

**Comment by art-lucas** [comment]
It works now! Thanks!
