### ISSUE TITLE
Pasteboard issue with Ulauncher, CopyQ, ulauncher-clipboard and ulauncher-two-factor-authenticator

### ISSUE THREAD

**Issue by art-lucas** [endorama/ulauncher-two-factor-authenticator#6]
I'm not sure this is the right place to report this issue.
I'm using Ubuntu 22.04 with `Ulauncher` and `CopyQ` as well as `ulauncher-clipboard` (https://github.com/friday/ulauncher-clipboard). I've also installed and activated the Ulauncher extension two-factor-authenticator, which is now working well.
CopyQ works as intended, and so does `ulauncher-clipboard`.
However, after launching Ulauncher, activating two-factor-authenticator (keyword: `2fa`), and hitting `Enter` or `Alt+1` to select the first entry, there's nothing in the clipboard, i.e., `CopyQ`/ `ulauncher-clipboard`.
Any idea how to fix/debug this will be much appreciated.

**Comment by tukanos** [comment]
> I'm not sure this is the right place to report this issue. I'm using Ubuntu 22.04 with `Ulauncher` and `CopyQ` as well as `ulauncher-clipboard` (https://github.com/friday/ulauncher-clipboard). I've also installed and activated the Ulauncher extension two-factor-authenticator, which is now working well. CopyQ works as intended, and so does `ulauncher-clipboard`. However, after launching Ulauncher, activating two-factor-authenticator (keyword: `2fa`), and hitting `Enter` or `Alt+1` to select the first entry, there's nothing in the clipboard, i.e., `CopyQ`/ `ulauncher-clipboard`. Any idea how to fix/debug this will be much appreciated.

I'm using the same combination.  I have created the PR, where I renamed the command.  When I create `2ami add TestService` and used the 2ami fake secret `ORSXG5A=` it works correctly now.  If I enter in ulauncher `2fa t` (as TestService) it shows the TestService and gnerates an OTP code which is saved into a clipboard (it is visible in both CopyQ and ulanucher-clipboard).

**Comment by art-lucas** [comment]
First of all, thanks a lot for replying to my request. I ended up removing the extension because I couldn't get it to work. I'd love to use it as it should be simpler to use than the Authenticator App which requires more steps.
Would you mind to elaborate the steps you took to make it work? I don't understand what "PR" is? Also, what do you mean by "create `2ami add TestService` and used the 2ami fake secret `ORSXG5A=` it works correctly now"?
I actually renamed the exec to `2ami`, which is fine, added the 2FA code with the `add` command, but I'm not getting anything in the clipboard.

**Comment by tukanos** [comment]
> ally renamed the exec to `2ami`, which is fine, added the 2FA

Did you follow the [getting started](https://github.com/endorama/2ami/wiki/Getting-Started) from the 2ami?  Does it work in the command line?  I have used the fake secret from the getting started wiki and it correctly generated and copied the code.

PR is short for pull request.  This is a way you can contribute to to a project on github.

**Comment by art-lucas** [comment]
2ami basically works, it has from the start. The only thing that doesn't is the copy of the result/output to the clipboard, i.e., it is always emply. I mean, while using Ulauncher+CopyQ.

**Comment by art-lucas** [comment]
Well, @endorama, I don't know what you did, but it works now! Thanks a million.

**Comment by endorama** [comment]
I suspect the reason was related to the underlying `2fa` binary, which have been fixed with the last update.

Glad it's solved and thank you for using this extension!

I'll close this issue but feel free to reopen if the problem appears again.
